### ISSUE TITLE
Search by inscription ID

### ISSUE THREAD

**Issue by Snorresk** [fralik/rundata-net#10]
Try to make it more simple to write several ID in a row. Take away $ and | ? if it is possible

**Comment by fralik** [comment]
Made it like this:
![image](https://github.com/user-attachments/assets/76bfc969-07b7-43b3-946b-1517266d5cd2)

**Comment by fralik** [comment]
@Snorresk , also added this:
![image](https://github.com/user-attachments/assets/6fe1973b-5fb5-4fa6-aad0-74253de258f3)
