### ISSUE TITLE
Search by case

### ISSUE THREAD

**Issue by Snorresk** [fralik/rundata-net#11]
Change suggestion

search with case > search with upper case 

About ”ignore upper case”. What does it mean? It seems like it works as ”search without case”.  It give results without upper case. Is it possible to allow rundata to make  a search both with and without upper case. Ignore uppre letters like we ignore () and [] in translitteration.

**Comment by fralik** [comment]
@Snorresk, there was no "ignore upper case".

Changed the wording a bit. It's now `Match case` and `Ignore case`. Differences are in the images below.
![image](https://github.com/user-attachments/assets/80cffb25-a437-42c7-b336-4ded7aa8b661)

![image](https://github.com/user-attachments/assets/9e0ba6bc-2a3e-4787-8793-589d5d03237b)

Have not been released yet.

**Comment by Snorresk** [comment]
Ok, let us release it )

**Comment by fralik** [comment]
I have automatic releases. Once issue is closed, website will be updated in ca 15 minutes.
